package com.netmera.extra;

public class Constants {
	public static final String SECURITY_KEY = "WVhCd1ZYSnNQV2gwZEhBbE0wRWxNa1lsTWtZNU1EUTBOelk0Tmk1dVpYUnRaWEpoTG1OdmJTVXpRVGd3SlRKR2JXOWlhVzFsY21FbE1rWm5ZV1JuWlhRbE1rWm9iMjFsTG5odGJDWnViVk5wZEdWVmNtdzlhSFIwY0NVelFTVXlSaVV5Umprd05EUTNOamcyTG01bGRHMWxjbUV1WTI5dEpUTkJPREFtYlc5a2RXeGxTV1E5TlRJNE5pWmhjSEJKWkQwNU1EUTBOelk0TmladWJWUmxiWEJzWVhSbFBXMXZZbWwwWlcxd2JHRjBaU1p2ZDI1bGNrbGtQV0Z3Y0hNbVpHOXRZV2x1UFc1bGRHMWxjbUV1WTI5dEptNXRVMmwwWlQwNU1EUTBOelk0TmladmQyNWxjbEp2YkdWVWVYQmxQVEVtZG1sbGQyVnlVbTlzWlZSNWNHVTlNU1oyYVdWM1pYSkpaRDFoY0hCekpn";
	public static final Double latitudeofIstanbul = 41.016174;
	public static final Double longitudeofIstanbul = 28.998413;

}
